version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postges
      POSTGRES_PASSWORD: password
      POSTGRES_DB: savings
    volumes:
       - ./data:/var/lib/postgresql/data