basePath: /api
definitions:
  request.CreateAccountRequest:
    properties:
      nama:
        type: string
      nik:
        minLength: 6
        type: string
      no_hp:
        maxLength: 12
        minLength: 11
        type: string
    required:
    - nama
    - nik
    - no_hp
    type: object
  request.CreateTrasaction:
    properties:
      no_rekening:
        type: string
      nominal:
        type: number
    required:
    - no_rekening
    - nominal
    type: object
  response.CreateAccountResponse:
    properties:
      nik:
        type: string
      no_hp:
        type: string
      no_rekening:
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      message:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a Rest Saving server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Swagger Saving API
  version: "2.0"
paths:
  /daftar:
    post:
      consumes:
      - application/json
      description: Create Account
      parameters:
      - description: Account Request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CreateAccountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.CreateAccountResponse'
      summary: create Account
  /saldo/{no_rekening}:
    get:
      consumes:
      - application/json
      description: Get Detail of Saldo
      parameters:
      - description: no_rekening
        in: path
        name: no_rekening
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: Province Not Found
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get Detail Saldo
  /tabung:
    post:
      consumes:
      - application/json
      description: Create Add Transaction Saving
      parameters:
      - description: Account Request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.CreateTrasaction'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: create Add Transaction Saving
  /tarik:
    post:
      consumes:
      - application/json
      description: Create Add Transaction Widraw
      parameters:
      - description: Account Request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.CreateTrasaction'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: create Add Transaction Widraw
schemes:
- http
swagger: "2.0"
